import os
import subprocess
import shutil
import re
import logging

import logging

# 1. Get the logger instance
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)  # Set the lowest level the logger will handle

# 2. Create a formatter
# This defines the format of your log messages. Create it once.
formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")

# 3. Create and configure the File Handler (fh)
fh = logging.FileHandler("file_parameterization.log")
fh.setLevel(logging.INFO)  # Set level for this specific handler
fh.setFormatter(formatter)  # Attach the formatter to this handler

# 4. Create and configure the Console/Stream Handler (ch)
# ch = logging.StreamHandler()
# ch.setLevel(logging.INFO) # Set level for this specific handler
# ch.setFormatter(formatter)  # Attach the same formatter

# 5. Add the configured handlers to the logger
# IMPORTANT: The logger needs to know about the handlers
logger.addHandler(fh)
# logger.addHandler(ch)


ROOT_DIR = r"C:\Users\punitkumar.more\Documents\Elisa\gcp_de\AUTOMATION\fdw-dev\fdw-dags\fdw\sql\KAIKU"
GIT_REPO = r"C:\Users\punitkumar.more\Documents\Elisa\fdw-dev\fdw-dags\fdw\sql\KAIKU"


COMMIT_MESSAGE = "Replacing hardcoded PROJECT_ID with PARAMETERIZED variable"

# dataset repalcement
# REPLACEMETN_STRING={'SVOC_SOR.SOR_GL_CUSTOMER':'GL_SOR.SOR_GL_CUSTOMER','KAIKU_STG.SOR_GL_CUSTOMER':'GL_SOR.SOR_GL_CUSTOMER','dmgcp-del-170.' : "",'cdw-dev-6933.': "",'cdw-qa-8380.':"",'fdw-qa-1054.':"",'fdw-dev-5780.': "",'{CDW_PROJECT_ID}.' : "" ,'{FDW_PROJECT_ID}.' : "",'{ODW_PROJECT_ID}.':"",'{GCP_PROJECT_ID}.' : "",'FDW_TEMP.': '{GCP_PROJECT_ID}.FDW_TEMP.','GL_SOR.':'{GCP_PROJECT_ID}.GL_SOR.','CENS_STG.' : '{CDW_PROJECT_ID}.CENS_STG.','CORPORATE_BUS.' : '{CDW_PROJECT_ID}.CORPORATE_BUS.','ETL.' : '{CDW_PROJECT_ID}.ETL.','FIRA_STG.' : '{CDW_PROJECT_ID}.FIRA_STG.','INTEGRATION_STG.' : '{GCP_PROJECT_ID}.INTEGRATION_STG.','JPD_FL.' : '{CDW_PROJECT_ID}.JPD_FL.', 'KAIKU_DM.' : '{GCP_PROJECT_ID}.KAIKU_DM.','KAIKU_STG.' : '{GCP_PROJECT_ID}.KAIKU_STG.','MANKELI_OWNER.' : '{GCP_PROJECT_ID}.MANKELI_OWNER.','MDM_DQ.' : '{GCP_PROJECT_ID}.MDM_DQ.','MIPA_FL.' : '{CDW_PROJECT_ID}.MIPA_FL.','ODW_BUS.' : '{ODW_PROJECT_ID}.ODW_BUS.','ODW_BUS3.' : '{ODW_PROJECT_ID}.ODW_BUS3.','ODW_BUS4.' : '{ODW_PROJECT_ID}.ODW_BUS4.','ODW_DM.' : '{ODW_PROJECT_ID}.ODW_DM.','ODW_FL.' : '{ODW_PROJECT_ID}.ODW_FL.','ODW_SOR.' : '{ODW_PROJECT_ID}.ODW_SOR.','ODW_SOR2.' : '{ODW_PROJECT_ID}.ODW_SOR2.','ODW_STG.' : '{ODW_PROJECT_ID}.ODW_STG.','ODW_STG2.' : '{ODW_PROJECT_ID}.ODW_STG2.','SFDC_FL.' : '{CDW_PROJECT_ID}.SFDC_FL.','SVOC_BUS.' : '{CDW_PROJECT_ID}.SVOC_BUS.','SVOC_SOR.' : '{CDW_PROJECT_ID}.SVOC_SOR.','SVOC_STG.'  : '{CDW_PROJECT_ID}.SVOC_STG.','TELLUS_FL.' : '{CDW_PROJECT_ID}.TELLUS_FL.','TERRA_BUS.' : '{CDW_PROJECT_ID}.TERRA_BUS.','TERRA_SOR.' : '{CDW_PROJECT_ID}.TERRA_SOR.'}

# project id replacement
# REPLACEMETN_STRING={'{CDW_PROJECT_ID}.' : 'cdw-qa-8380.', '{GCP_PROJECT_ID}.':'fdw-qa-1054.', '{ODW_PROJECT_ID}.':'odw-qa-3094.'}
# REPLACEMETN_STRING={'{CDW_PROJECT_ID}.' : 'cdw-prod-6040.', '{GCP_PROJECT_ID}.':'fdw-prod-5288.', '{ODW_PROJECT_ID}.':'odw-prod-4581.'}
# REPLACEMETN_STRING={'cdw-qa-8380.':'{CDW_PROJECT_ID}.', 'fdw-qa-1054':'{GCP_PROJECT_ID}', 'odw-qa-3094':'{ODW_PROJECT_ID}'}
# REPLACEMETN_STRING={'cdw-qa-8380.':'', 'fdw-qa-1054':'', 'odw-qa-3094':'', 'cdw-prod-6040.':'', 'fdw-prod-5288.':'', 'odw-qa-3094.':''}
# REPLACEMETN_STRING={'cdw-prod-6040.':'cdw-qa-8380.', 'fdw-prod-5288.':'fdw-qa-1054.', 'odw-prod-4581.':'odw-qa-3094.'}
REPLACEMETN_STRING = {
    "cdw-qa-8380.": "cdw-prod-6040.",
    "fdw-qa-1054.": "fdw-prod-5288.",
    "odw-qa-3094.": "odw-prod-4581.",
}

# view replacement
# REPLACEMETN_STRING={'{GCP_PROJECT_ID}.KAIKU_STG.BUS_BASSET_RATED':'{GCP_PROJECT_ID}.odw_kaiku.BUS_BASSET_RATED', '{GCP_PROJECT_ID}.KAIKU_STG.BUS_TELLUS_HIST':'{GCP_PROJECT_ID}.odw_kaiku.BUS_TELLUS_HIST', '{GCP_PROJECT_ID}.KAIKU_STG.BUS_TELLUS_RATED':'{GCP_PROJECT_ID}.odw_kaiku.BUS_TELLUS_RATED', '{GCP_PROJECT_ID}.KAIKU_STG.DATA_MIPA_SOPIMUSTUOTE':'{GCP_PROJECT_ID}.cdw_kaiku.DATA_MIPA_SOPIMUSTUOTE', '{GCP_PROJECT_ID}.KAIKU_STG.DIM_BASSET_CALLTYPE':'{GCP_PROJECT_ID}.odw_kaiku.DIM_BASSET_CALLTYPE', '{GCP_PROJECT_ID}.KAIKU_STG.DIM_BASSET_CUSTOMER':'{GCP_PROJECT_ID}.odw_kaiku.DIM_BASSET_CUSTOMER', '{GCP_PROJECT_ID}.KAIKU_STG.DIM_MIPA_SOPIMUSHIER':'{GCP_PROJECT_ID}.cdw_kaiku.DIM_MIPA_SOPIMUSHIER', '{GCP_PROJECT_ID}.KAIKU_STG.FCT_CONTRACT_SALES_T':'{GCP_PROJECT_ID}.cdw_kaiku.FCT_CONTRACT_SALES_T', '{GCP_PROJECT_ID}.KAIKU_STG.FCT_FIXED_SALES_T':'{GCP_PROJECT_ID}.cdw_kaiku.FCT_FIXED_SALES_T', '{GCP_PROJECT_ID}.KAIKU_STG.FCT_MOBILE_SALES_T':'{GCP_PROJECT_ID}.cdw_kaiku.FCT_MOBILE_SALES_T', '{GCP_PROJECT_ID}.KAIKU_STG.FL_ABP_BL9_BLNG_ARRANGEMENT_EXT':'{GCP_PROJECT_ID}.cdw_kaiku.FL_ABP_BL9_BLNG_ARRANGEMENT_EXT', '{GCP_PROJECT_ID}.KAIKU_STG.FL_EMCE_NETEZZA_COMPANY_VIEW':'{GCP_PROJECT_ID}.cdw_kaiku.FL_EMCE_NETEZZA_COMPANY_VIEW', '{GCP_PROJECT_ID}.KAIKU_STG.FL_EMCE_STG_U_BILLING_CARD':'{GCP_PROJECT_ID}.cdw_kaiku.FL_EMCE_STG_U_BILLING_CARD', '{GCP_PROJECT_ID}.KAIKU_STG.FL_EMCE_STG_U_BUSINESS_PRODUCT':'{GCP_PROJECT_ID}.cdw_kaiku.FL_EMCE_STG_U_BUSINESS_PRODUCT', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_CHANGE_SIM_ORDER':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_CHANGE_SIM_ORDER', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_DEVICEORDER':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_DEVICEORDER', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_GSMORDERS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_GSMORDERS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_HANDSETORDER':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_HANDSETORDER', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_NODE':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_NODE', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_PROFILE_VALUES_DATA':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_PROFILE_VALUES_DATA', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_DISCOUNTS_USES':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_DISCOUNTS_USES', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_ELISA_ORDER_DETAILS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_ELISA_ORDER_DETAILS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_ORDER_PRODUCTS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_ORDER_PRODUCTS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_ORDERS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_ORDERS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_ORDER_GROUP_DELIVERY':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_ORDER_GROUP_DELIVERY', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_PHYSICALSIM':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_PHYSICALSIM', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_PRODUCT_ORDER_GROUP':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_PRODUCT_ORDER_GROUP', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_PRODUCT_ORDER_ITEM':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_PRODUCT_ORDER_ITEM', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_STOCK_ITEM':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_STOCK_ITEM', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_TICKETS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_TICKETS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_TITO_AGENT_ACTIONS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_TITO_AGENT_ACTIONS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_MIPA_TLAJIM':'{GCP_PROJECT_ID}.cdw_kaiku.FL_MIPA_TLAJIM', '{GCP_PROJECT_ID}.KAIKU_STG.FL_MIPA_TTILAUS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_MIPA_TTILAUS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_MIPA_TTITUOTE':'{GCP_PROJECT_ID}.cdw_kaiku.FL_MIPA_TTITUOTE', '{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_ACCOUNT_COST':'{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_ACCOUNT_COST', '{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_PAYMENT_REFILL':'{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_PAYMENT_REFILL', '{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_SERVICE_FEE':'{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_SERVICE_FEE', '{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_ORDER_PRODUCT':'{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_ORDER_PRODUCT', '{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_ORDERS':'{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_ORDERS', '{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_SERVICE_LINE_ITEM':'{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_SERVICE_LINE_ITEM', '{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_SERVICES':'{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_SERVICES', '{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_SUBSCRIPTION':'{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_SUBSCRIPTION', '{GCP_PROJECT_ID}.KAIKU_STG.LKP_ABP_CUSTOMER':'{GCP_PROJECT_ID}.cdw_kaiku.LKP_ABP_CUSTOMER', '{GCP_PROJECT_ID}.KAIKU_STG.R_FCHD_KASITTELY':'{GCP_PROJECT_ID}.cdw_kaiku.R_FCHD_KASITTELY', '{GCP_PROJECT_ID}.KAIKU_STG.R_FCHD_TIKETTI':'{GCP_PROJECT_ID}.cdw_kaiku.R_FCHD_TIKETTI', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_AR1_ACCOUNT':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_AR1_ACCOUNT', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_AR1_CHARGE_GROUP_VIEW':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_AR1_CHARGE_GROUP_VIEW', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_AR1_INVOICE':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_AR1_INVOICE', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_CONTRACT':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_CONTRACT', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_GL_CUSTOMER':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_GL_CUSTOMER', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_INVOICE':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_INVOICE', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_INVOICE_HEADER':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_INVOICE_HEADER', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_INVOICE_ROW':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_INVOICE_ROW', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_PARTY':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_PARTY', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_PARTY_CONTRACT':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_PARTY_CONTRACT', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_PREPAID_CRS_USAGE':'{GCP_PROJECT_ID}.odw_kaiku.SOR_PREPAID_CRS_USAGE', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_PRODUCT':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_PRODUCT', '{GCP_PROJECT_ID}.KAIKU_STG.SOR_SALES_ITEM':'{GCP_PROJECT_ID}.cdw_kaiku.SOR_SALES_ITEM', '{GCP_PROJECT_ID}.KAIKU_STG.ST_COMFONE_INBOUND':'{GCP_PROJECT_ID}.odw_kaiku.ST_COMFONE_INBOUND', '{GCP_PROJECT_ID}.KAIKU_STG.ST_COMFONE_OUTBOUND':'{GCP_PROJECT_ID}.odw_kaiku.ST_COMFONE_OUTBOUND', '{GCP_PROJECT_ID}.KAIKU_STG.ST_REP_OE_DEVICE_ORDER':'{GCP_PROJECT_ID}.cdw_kaiku.ST_REP_OE_DEVICE_ORDER', '{GCP_PROJECT_ID}.KAIKU_STG.ST_REP_OE_DEVICE_ORDER_ROW':'{GCP_PROJECT_ID}.cdw_kaiku.ST_REP_OE_DEVICE_ORDER_ROW', '{GCP_PROJECT_ID}.KAIKU_STG.ST_SAP_MBEW':'{GCP_PROJECT_ID}.cdw_kaiku.ST_SAP_MBEW', '{GCP_PROJECT_ID}.KAIKU_STG.TEC_SIS_SMS':'{GCP_PROJECT_ID}.odw_kaiku.TEC_SIS_SMS', '{GCP_PROJECT_ID}.KAIKU_STG.TEC_SMSC_SMS':'{GCP_PROJECT_ID}.odw_kaiku.TEC_SMSC_SMS', '{GCP_PROJECT_ID}.KAIKU_STG.V_MONTHLY_ABP_GLE_INFO':'{GCP_PROJECT_ID}.cdw_kaiku.V_MONTHLY_ABP_GLE_INFO', '{GCP_PROJECT_ID}.KAIKU_STG.OTSO_COSTS_FOR_KAIKU':'{GCP_PROJECT_ID}.cdw_kaiku.OTSO_COSTS_FOR_KAIKU', '{GCP_PROJECT_ID}.KAIKU_STG.FACT_GPRS':'{GCP_PROJECT_ID}.odw_kaiku.FACT_GPRS', '{GCP_PROJECT_ID}.KAIKU_STG.FACT_MSC':'{GCP_PROJECT_ID}.odw_kaiku.FACT_MSC', '{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_VOUCHER_REFILL':'{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_VOUCHER_REFILL'}


# table replacement
# REPLACEMETN_STRING={'{ODW_PROJECT_ID}.ODW_BUS.BUS_SMS' : '{GCP_PROJECT_ID}.odw_kaiku.BUS_SMS','{ODW_PROJECT_ID}.ODW_BUS.BUS_TAP' : '{GCP_PROJECT_ID}.odw_kaiku.BUS_TAP','{ODW_PROJECT_ID}.ODW_DM.FACT_NW_QUALITY_MONTH' : '{GCP_PROJECT_ID}.odw_kaiku.FACT_NW_QUALITY_MONTH','{ODW_PROJECT_ID}.ODW_LOOKUP.SOR_EDR_USER' : '{GCP_PROJECT_ID}.odw_kaiku.SOR_EDR_USER','{ODW_PROJECT_ID}.ODW_LOOKUP.SOR_EDR_USER_EDR' : '{GCP_PROJECT_ID}.odw_kaiku.SOR_EDR_USER_EDR','{ODW_PROJECT_ID}.ODW_SOR2.SOR_MOBIN_CALL' : '{GCP_PROJECT_ID}.odw_kaiku.SOR_MOBIN_CALL','{ODW_PROJECT_ID}.ODW_SOR2.SOR_MOBIN_CON_CONP' : '{GCP_PROJECT_ID}.odw_kaiku.SOR_MOBIN_CON_CONP','{CDW_PROJECT_ID}.SVOC_STG.FL_JPD_HANDSETMODEL' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_HANDSETMODEL','{CDW_PROJECT_ID}.SVOC_STG.FL_JPD_INTRATUNNUS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_INTRATUNNUS','{CDW_PROJECT_ID}.SVOC_STG.FL_JPD_SAP_DELIVERY' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_SAP_DELIVERY','{CDW_PROJECT_ID}.SVOC_BUS.FCT_CONTRACT_BASE_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_CONTRACT_BASE_T','{CDW_PROJECT_ID}.SVOC_BUS.FCT_CONTRACT_CHURN_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_CONTRACT_CHURN_T','{CDW_PROJECT_ID}.SVOC_BUS.FCT_FIXED_BASE_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_FIXED_BASE_T','{CDW_PROJECT_ID}.SVOC_BUS.FCT_FIXED_CHURN_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_FIXED_CHURN_T','{CDW_PROJECT_ID}.SVOC_BUS.FCT_MOBILE_BASE_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_MOBILE_BASE_T','{CDW_PROJECT_ID}.SVOC_BUS.FCT_MOBILE_CHURN_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_MOBILE_CHURN_T','{CDW_PROJECT_ID}.SVOC_SOR.SOR_CONTRACT_REL' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_CONTRACT_REL','{CDW_PROJECT_ID}.SVOC_SOR.SOR_DEVICE_MODEL' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_DEVICE_MODEL','{CDW_PROJECT_ID}.SVOC_SOR.SOR_SALES' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_SALES','{CDW_PROJECT_ID}.CORPORATE_BUS.COMPANY' : '{GCP_PROJECT_ID}.cdw_kaiku.COMPANY','{CDW_PROJECT_ID}.CORPORATE_BUS.ST_MDM_ID_COMPANY' : '{GCP_PROJECT_ID}.cdw_kaiku.ST_MDM_ID_COMPANY','{CDW_PROJECT_ID}.SFDC_FL.FL_SFDC_ACCOUNT' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_ACCOUNT','{CDW_PROJECT_ID}.TERRA_BUS.DIM_BILLING_ARRANGEMENT' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_BILLING_ARRANGEMENT','{CDW_PROJECT_ID}.TERRA_BUS.DIM_CHARGE' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_CHARGE','{CDW_PROJECT_ID}.TERRA_BUS.DIM_CUSTOMER' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_CUSTOMER','{CDW_PROJECT_ID}.TERRA_BUS.DIM_SUBSCRIBER' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_SUBSCRIBER','{CDW_PROJECT_ID}.TERRA_BUS.FACT_CREDIT_LOSS' : '{GCP_PROJECT_ID}.cdw_kaiku.FACT_CREDIT_LOSS','{CDW_PROJECT_ID}.TERRA_BUS.DIM_CLASSIFICATION' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_CLASSIFICATION','{CDW_PROJECT_ID}.SVOC_STG.FL_JPD_DEVICEORDER' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_DEVICEORDER','{CDW_PROJECT_ID}.SVOC_STG.FL_JPD_HANDSETORDER' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_HANDSETORDER','{CDW_PROJECT_ID}.SVOC_SOR.SOR_CONTRACT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_CONTRACT','{CDW_PROJECT_ID}.SVOC_SOR.SOR_PARTY' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_PARTY','{CDW_PROJECT_ID}.SVOC_SOR.SOR_PARTY_CONTRACT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_PARTY_CONTRACT','{CDW_PROJECT_ID}.SVOC_SOR.SOR_PRODUCT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_PRODUCT'}


# new_table_list
# REPLACEMETN_STRING = {'{GCP_PROJECT_ID}.KAIKU_STG.BUS_BASSET_RATED' : '{GCP_PROJECT_ID}.odw_kaiku.BUS_BASSET_RATED','{GCP_PROJECT_ID}.KAIKU_STG.BUS_TELLUS_HIST' : '{GCP_PROJECT_ID}.odw_kaiku.BUS_TELLUS_HIST','{GCP_PROJECT_ID}.KAIKU_STG.BUS_TELLUS_RATED' : '{GCP_PROJECT_ID}.odw_kaiku.BUS_TELLUS_RATED','{GCP_PROJECT_ID}.KAIKU_STG.DATA_MIPA_SOPIMUSTUOTE' : '{GCP_PROJECT_ID}.cdw_kaiku.DATA_MIPA_SOPIMUSTUOTE','{GCP_PROJECT_ID}.KAIKU_STG.DIM_BASSET_CALLTYPE' : '{GCP_PROJECT_ID}.odw_kaiku.DIM_BASSET_CALLTYPE','{GCP_PROJECT_ID}.KAIKU_STG.DIM_BASSET_CUSTOMER' : '{GCP_PROJECT_ID}.odw_kaiku.DIM_BASSET_CUSTOMER','{GCP_PROJECT_ID}.KAIKU_STG.DIM_MIPA_SOPIMUSHIER' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_MIPA_SOPIMUSHIER','{GCP_PROJECT_ID}.KAIKU_STG.FCT_CONTRACT_SALES_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_CONTRACT_SALES_T','{GCP_PROJECT_ID}.KAIKU_STG.FCT_FIXED_SALES_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_FIXED_SALES_T','{GCP_PROJECT_ID}.KAIKU_STG.FCT_MOBILE_SALES_T' : '{GCP_PROJECT_ID}.cdw_kaiku.FCT_MOBILE_SALES_T','{GCP_PROJECT_ID}.KAIKU_STG.FL_ABP_BL9_BLNG_ARRANGEMENT_EXT' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_ABP_BL9_BLNG_ARRANGEMENT_EXT','{GCP_PROJECT_ID}.KAIKU_STG.FL_EMCE_NETEZZA_COMPANY_VIEW' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_EMCE_NETEZZA_COMPANY_VIEW','{GCP_PROJECT_ID}.KAIKU_STG.FL_EMCE_STG_U_BILLING_CARD' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_EMCE_STG_U_BILLING_CARD','{GCP_PROJECT_ID}.KAIKU_STG.FL_EMCE_STG_U_BUSINESS_PRODUCT' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_EMCE_STG_U_BUSINESS_PRODUCT','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_CHANGE_SIM_ORDER' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_CHANGE_SIM_ORDER','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_DEVICEORDER' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_DEVICEORDER','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_GSMORDERS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_GSMORDERS','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_HANDSETORDER' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_HANDSETORDER','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_NODE' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_NODE','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_PROFILE_VALUES_DATA' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_PROFILE_VALUES_DATA','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_DISCOUNTS_USES' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_DISCOUNTS_USES','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_ELISA_ORDER_DETAILS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_ELISA_ORDER_DETAILS','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_ORDER_PRODUCTS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_ORDER_PRODUCTS','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_KIRJA_UC_ORDERS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_KIRJA_UC_ORDERS','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_ORDER_GROUP_DELIVERY' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_ORDER_GROUP_DELIVERY','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_PHYSICALSIM' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_PHYSICALSIM','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_PRODUCT_ORDER_GROUP' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_PRODUCT_ORDER_GROUP','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_PRODUCT_ORDER_ITEM' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_PRODUCT_ORDER_ITEM','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_STOCK_ITEM' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_STOCK_ITEM','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_TICKETS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_TICKETS','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_TITO_AGENT_ACTIONS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_TITO_AGENT_ACTIONS','{GCP_PROJECT_ID}.KAIKU_STG.FL_MIPA_TLAJIM' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_MIPA_TLAJIM','{GCP_PROJECT_ID}.KAIKU_STG.FL_MIPA_TTILAUS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_MIPA_TTILAUS','{GCP_PROJECT_ID}.KAIKU_STG.FL_MIPA_TTITUOTE' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_MIPA_TTITUOTE','{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_ACCOUNT_COST' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_ACCOUNT_COST','{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_PAYMENT_REFILL' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_PAYMENT_REFILL','{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_SERVICE_FEE' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_SERVICE_FEE','{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_ORDER_PRODUCT' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_ORDER_PRODUCT','{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_ORDERS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_ORDERS','{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_SERVICE_LINE_ITEM' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_SERVICE_LINE_ITEM','{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_SERVICES' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_SERVICES','{GCP_PROJECT_ID}.KAIKU_STG.FL_SFDC_SUBSCRIPTION' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_SFDC_SUBSCRIPTION','{GCP_PROJECT_ID}.KAIKU_STG.LKP_ABP_CUSTOMER' : '{GCP_PROJECT_ID}.cdw_kaiku.LKP_ABP_CUSTOMER','{GCP_PROJECT_ID}.KAIKU_STG.R_FCHD_KASITTELY' : '{GCP_PROJECT_ID}.cdw_kaiku.R_FCHD_KASITTELY','{GCP_PROJECT_ID}.KAIKU_STG.R_FCHD_TIKETTI' : '{GCP_PROJECT_ID}.cdw_kaiku.R_FCHD_TIKETTI','{GCP_PROJECT_ID}.KAIKU_STG.SOR_AR1_ACCOUNT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_AR1_ACCOUNT','{GCP_PROJECT_ID}.KAIKU_STG.SOR_AR1_CHARGE_GROUP_VIEW' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_AR1_CHARGE_GROUP_VIEW','{GCP_PROJECT_ID}.KAIKU_STG.SOR_AR1_INVOICE' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_AR1_INVOICE','{GCP_PROJECT_ID}.KAIKU_STG.SOR_CONTRACT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_CONTRACT','{GCP_PROJECT_ID}.KAIKU_STG.SOR_INVOICE' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_INVOICE','{GCP_PROJECT_ID}.KAIKU_STG.SOR_INVOICE_HEADER' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_INVOICE_HEADER','{GCP_PROJECT_ID}.KAIKU_STG.SOR_INVOICE_ROW' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_INVOICE_ROW','{GCP_PROJECT_ID}.KAIKU_STG.SOR_PARTY' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_PARTY','{GCP_PROJECT_ID}.KAIKU_STG.SOR_PARTY_CONTRACT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_PARTY_CONTRACT','{GCP_PROJECT_ID}.KAIKU_STG.SOR_PREPAID_CRS_USAGE' : '{GCP_PROJECT_ID}.odw_kaiku.SOR_PREPAID_CRS_USAGE','{GCP_PROJECT_ID}.KAIKU_STG.SOR_PRODUCT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_PRODUCT','{GCP_PROJECT_ID}.KAIKU_STG.SOR_SALES_ITEM' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_SALES_ITEM','{GCP_PROJECT_ID}.KAIKU_STG.ST_COMFONE_INBOUND' : '{GCP_PROJECT_ID}.odw_kaiku.ST_COMFONE_INBOUND','{GCP_PROJECT_ID}.KAIKU_STG.ST_COMFONE_OUTBOUND' : '{GCP_PROJECT_ID}.odw_kaiku.ST_COMFONE_OUTBOUND','{GCP_PROJECT_ID}.KAIKU_STG.ST_REP_OE_DEVICE_ORDER' : '{GCP_PROJECT_ID}.cdw_kaiku.ST_REP_OE_DEVICE_ORDER','{GCP_PROJECT_ID}.KAIKU_STG.ST_REP_OE_DEVICE_ORDER_ROW' : '{GCP_PROJECT_ID}.cdw_kaiku.ST_REP_OE_DEVICE_ORDER_ROW','{GCP_PROJECT_ID}.KAIKU_STG.ST_SAP_MBEW' : '{GCP_PROJECT_ID}.cdw_kaiku.ST_SAP_MBEW','{GCP_PROJECT_ID}.KAIKU_STG.TEC_SIS_SMS' : '{GCP_PROJECT_ID}.odw_kaiku.TEC_SIS_SMS','{GCP_PROJECT_ID}.KAIKU_STG.TEC_SMSC_SMS' : '{GCP_PROJECT_ID}.odw_kaiku.TEC_SMSC_SMS','{GCP_PROJECT_ID}.KAIKU_STG.V_MONTHLY_ABP_GLE_INFO' : '{GCP_PROJECT_ID}.KAIKU_STG.V_MONTHLY_ABP_GLE_INFO','{GCP_PROJECT_ID}.KAIKU_STG.V_SAP_MATERIAL_AVG_PRICE' : '{GCP_PROJECT_ID}.KAIKU_STG.V_SAP_MATERIAL_AVG_PRICE','{GCP_PROJECT_ID}.KAIKU_STG.V_STG_SVOC_SOR_CONTRACT_PARTY' : '{GCP_PROJECT_ID}.KAIKU_STG.V_STG_SVOC_SOR_CONTRACT_PARTY','{ODW_PROJECT_ID}.ODW_BUS.BUS_MOBDATA' : '{GCP_PROJECT_ID}.odw_kaiku.BUS_MOBDATA','{ODW_PROJECT_ID}.ODW_BUS.VIEW_TELLUS_INLA2' : '{GCP_PROJECT_ID}.odw_kaiku.VIEW_TELLUS_INLA2','{ODW_PROJECT_ID}.ODW_BUS.VIEW_TELLUS_TVR' : '{GCP_PROJECT_ID}.odw_kaiku.VIEW_TELLUS_TVR','{ODW_PROJECT_ID}.ODW_SOR2.IN_CALLS' : '{GCP_PROJECT_ID}.odw_kaiku.IN_CALLS','{CDW_PROJECT_ID}.SVOC_BUS.DIM_PARTY_HIST' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_PARTY_HIST','{CDW_PROJECT_ID}.SVOC_BUS.DIM_PARTY_SALESPERSON_JPD' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_PARTY_SALESPERSON_JPD','{CDW_PROJECT_ID}.TERRA_BUS.DIM_UECC_AGENT' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_UECC_AGENT','{CDW_PROJECT_ID}.TERRA_BUS.DIM_UECC_AGENT_LOGIN' : '{GCP_PROJECT_ID}.cdw_kaiku.DIM_UECC_AGENT_LOGIN','{CDW_PROJECT_ID}.TERRA_BUS.SOR_PRODUCT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_PRODUCT','{CDW_PROJECT_ID}.TERRA_BUS.SOR_SERVICE_AGREEMENT' : '{GCP_PROJECT_ID}.cdw_kaiku.SOR_SERVICE_AGREEMENT','{CDW_PROJECT_ID}.TERRA_BUS.V_SOR_ELISA_JPD_MNP' : '{GCP_PROJECT_ID}.cdw_kaiku.V_SOR_ELISA_JPD_MNP','{CDW_PROJECT_ID}.TERRA_SOR.V_SVOC_SOR_PRODUCT' : '{GCP_PROJECT_ID}.cdw_kaiku.V_SVOC_SOR_PRODUCT','{GCP_PROJECT_ID}.KAIKU_STG.OTSO_COSTS_FOR_KAIKU' : '{GCP_PROJECT_ID}.cdw_kaiku.OTSO_COSTS_FOR_KAIKU','{GCP_PROJECT_ID}.KAIKU_STG.FACT_GPRS' : '{GCP_PROJECT_ID}.odw_kaiku.FACT_GPRS','{GCP_PROJECT_ID}.KAIKU_STG.FACT_MSC' : '{GCP_PROJECT_ID}.odw_kaiku.FACT_MSC','{GCP_PROJECT_ID}.KAIKU_STG.FL_PREPAID_VOUCHER_REFILL' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_PREPAID_VOUCHER_REFILL','{GCP_PROJECT_ID}.KAIKU_STG.FL_JPD_BILLINGITEMORDER' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_BILLINGITEMORDER','{GCP_PROJECT_ID}.KAIKU_STG.DL_JPD_ORDERS' : '{GCP_PROJECT_ID}.cdw_kaiku.DL_JPD_ORDERS','{GCP_PROJECT_ID}.KAIKU_STG.DL_JPD_ORDERPARAMS' : '{GCP_PROJECT_ID}.cdw_kaiku.DL_JPD_ORDERPARAMS'}


# REPLACEMETN_STRING = {'{CDW_PROJECT_ID}.JPD_FL.FL_JPD_TICKET_CATEGORY' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_TICKET_CATEGORY','{CDW_PROJECT_ID}.JPD_FL.FL_JPD_TICKETS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_TICKETS','{CDW_PROJECT_ID}.JPD_FL.FL_JPD_GSM' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_GSM','{CDW_PROJECT_ID}.JPD_FL.FL_JPD_GSMORDERS' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_GSMORDERS','{CDW_PROJECT_ID}.JPD_FL.FL_JPD_LOGICALSIM' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_LOGICALSIM','{CDW_PROJECT_ID}.JPD_FL.FL_JPD_PRODUCT' : '{GCP_PROJECT_ID}.cdw_kaiku.FL_JPD_PRODUCT','{ODW_PROJECT_ID}.ODW_SOR2.IN_CALLS' : '{GCP_PROJECT_ID}.odw_kaiku.SOR_IN_CALLS','{ODW_PROJECT_ID}.ODW_STG.ST_COMFONE_INBOUND' : '{GCP_PROJECT_ID}.odw_kaiku.ST_COMFONE_INBOUND','{ODW_PROJECT_ID}.ODW_STG.ST_COMFONE_OUTBOUND' : '{GCP_PROJECT_ID}.odw_kaiku.ST_COMFONE_OUTBOUND'}


def remove_multi_line_comment(full_file_path):
    with open(full_file_path, "r", encoding="utf-8") as f:
        content = f.read()
        original_content = content

    if content != original_content:
        with open(full_file_path, "w", encoding="utf-8") as f:
            content = re.sub(r"/\*\*.*?\*\*/--;", "", content, flags=re.DOTALL)
            f.write(content)
        return True
    else:
        print(f"No multiline comment found in file to replace {full_file_path}")


def repalce_in_file(full_file_path, REPLACEMETN_STRING):
    """Reads a file replaces string based on a dictionary, and write it back"""
    try:
        with open(full_file_path, "r", encoding="utf-8") as f:
            content = f.read()
            original_content = content

        for old_str, new_str in REPLACEMETN_STRING.items():
            content = content.replace(old_str, new_str)

        if content != original_content:
            print(f"Found and replace content in {full_file_path}")
            with open(full_file_path, "w", encoding="utf-8") as f:
                f.write(content)
            return True

    except Exception as e:
        print(f"Error processing file {full_file_path}")

    # remove_multi_line_comment(full_file_path)


# def move_modified_files(ROOT_DIR, GIT_REPO):
#     print(f"ROOT_DIR : {ROOT_DIR}")
#     print(f"GIT_REPO : {GIT_REPO}")
#     try :
#         shutil.copytree(ROOT_DIR, GIT_REPO)
#         print(f"Successfully copied {ROOT_DIR} TO {GIT_REPO}")
#     except FileExistsError :
#         print(f"Error ")


# def git_commit_and_push(COMMIT_MESSAGE) :
#     """Stages, Commit and pushes changes to Git Repository"""
#     try :
#         print("Starting git operations-----")
#         print(f"1. Staging changes (git add .)....")
#         subprocess.run(["git", "add",'.'], check=True)
#         print(f'2. Commiting changes (git commit -m ) \"{COMMIT_MESSAGE}\"')
#         subprocess.run(["git", "commit" "-m", COMMIT_MESSAGE], check=True)
#         print(f'3. Pushing the changes to clone (git push).... ')
#         #subprocess.run(["git","push"],check=True)

#         print("Successfully commited and pushed changes to git")
#     except subprocess.CalledProcessError as e:
#         print(f"Error Occured during git operations")
#     except FileNotFoundError:
#         print("Git command not found. Is git installed in your system's path")


def main():
    """main fucntion to run replacement and git logic"""
    print(f"start search in directory : {ROOT_DIR}")
    print(f"Applying the following replacement")

    # for old, new in REPLACEMETN_STRING.items():
    #     print(f'Replacing {old} with {new}')

    file_changed_count = 0
    file_not_changed_count = 0
    file_changed_count_list = {}

    for root, dir, file_name in os.walk(ROOT_DIR):
        print(f"ROOT DIR : {root}")
        print(f"DIR : {dir}")
        print(f"files : {file_name}")
        print("--" * 30)
        for files in file_name:
            if files.endswith(".sql"):
                full_file_path = os.path.join(root, files)
                print(f"Full file path : {full_file_path}")

                if full_file_path.count("\\") != 13:
                    logger.info(f"Skipping invalid file path : {full_file_path}")
                    logger.debug("Invalid Path")
                    # --- Now you can use the logger ---
                    logger.info("This is an informational message.")
                    logger.warning("This is a warning message.")
                    continue

                if repalce_in_file(full_file_path, REPLACEMETN_STRING):
                    file_changed_count += 1
                    file_changed_count_list[file_changed_count] = full_file_path

                else:
                    file_not_changed_count += 1
                # if remove_multi_line_comment(full_file_path):
                # print(f"removed multi line comment from {full_file_path}")

    if file_changed_count > 0:
        print(
            f"print changed file count : {file_changed_count} and File name : {file_changed_count_list}"
        )
    else:
        print(f"No file changes count = {file_not_changed_count}")

    # move_modified_files(full_file_path, GIT_REPO)
    # git_commit_and_push(COMMIT_MESSAGE)


if __name__ == "__main__":
    main()

