import openpyxl
from openpyxl.styles import Font, PatternFill

# --- Input List of Workflows ---
INPUT_WF_LIST = ["FACT_SAP_REJECT"
    "MANKELI_NS.WF_FACT_ORDER",
    # "MANKELI_NS.WF_FACT_ORDER_ASSETS","MANKELI_NS.WF_FACT_SAP","MANKELI_NS.WF_FACT_SAP_LINE_ITEMS","MANKELI_NS.WF_SOR_ORDER_MASTER_ASSETS","MANKELI_NS.WF_SOR_ORDER_MASTER_TABLE","MANKELI_NS.WF_SOR_SAP_FI","MANKELI_NS.WF_SOR_SAP_MASTER_ACCT","MANKELI_NS.WF_SOR_SAP_PCA","MANKELI_NS.WF_ST_ANLA","MANKELI_NS.WF_ST_ANLP","MANKELI_NS.WF_ST_BKPF_BSEG","MANKELI_NS.WF_ST_GLPCA","MANKELI_NS.WF_ST_T095B","MANKELI_NS.WF_FACT_ORDER_01","MANKELI_NS.WF_FACT_ORDER_02","MANKELI_NS.WF_FACT_ORDER_03","MANKELI_NS.WF_FACT_ORDER_04","MANKELI_NS.WF_FACT_ORDER_05","MANKELI_NS.WF_FACT_ORDER_06","MANKELI_NS.WF_FACT_ORDER_07","MANKELI_NS.WF_FACT_ORDER_08","MANKELI_NS.WF_FACT_ORDER_09","MANKELI_NS.WF_FACT_ORDER_10","MANKELI_NS.WF_FACT_ORDER_11","MANKELI_NS.WF_FACT_ORDER_ASSETS_01","MANKELI_NS.WF_FACT_ORDER_ASSETS_02","MANKELI_NS.WF_FACT_ORDER_ASSETS_03","MANKELI_NS.WF_FACT_ORDER_ASSETS_04","MANKELI_NS.WF_FACT_ORDER_ASSETS_05","MANKELI_NS.WF_FACT_ORDER_ASSETS_06","MANKELI_NS.WF_FACT_ORDER_ASSETS_07","MANKELI_NS.WF_FACT_ORDER_ASSETS_08","MANKELI_NS.WF_FACT_ORDER_ASSETS_09","MANKELI_NS.WF_FACT_ORDER_ASSETS_10","MANKELI_NS.WF_FACT_ORDER_ASSETS_11","MANKELI_NS.WF_AP_ACTUALSTOANAPLAN_EXPENSES","MANKELI_NS.WF_AP_ACTUALSTOANAPLAN_SALES","MANKELI_NS.WF_FACT_COPA","MANKELI_NS.WF_FACT_PCA_BS","MANKELI_NS.WF_FACT_REVENUE_BY_PROD","MANKELI_NS.WF_SOR_SAP_COPA","MANKELI_NS.WF_SOR_SAP_COPA_NEW","MANKELI_NS.WF_ST_CE41000_CE11000","MANKELI_NS.WF_ST_CE41000_CE11000_NEW","MANKELI_NS.WF_AP_CAPEX_LE","MANKELI_NS.WF_AP_CAPEX_TUO_LE","MANKELI_NS.WF_AP_DEPRECIATIONS_LE","MANKELI_NS.WF_AP_DEPRECIATIONS_TUO_LE","MANKELI_NS.WF_AP_EXPENSES_IC_AND_ROAMING_LE","MANKELI_NS.WF_AP_EXPENSES_LE","MANKELI_NS.WF_AP_FTE_LE","MANKELI_NS.WF_AP_HY_GENERAL_SALES_LE","MANKELI_NS.WF_AP_JOURNAL_ACT","MANKELI_NS.WF_AP_KEYFIGURE_ACT","MANKELI_NS.WF_AP_KEYFIGURE_LE","MANKELI_NS.WF_AP_OPERATOR_SALES_LE","MANKELI_NS.WF_AP_OTHER_INCOME_LE","MANKELI_NS.WF_AP_REVENUE_IC_AND_ROAMING_LE","MANKELI_NS.WF_AP_SALES_ABPU_LE","MANKELI_NS.WF_AP_SALES_BY_ACCOUNT_LE","MANKELI_NS.WF_AP_SALES_VOLUME_LE","MANKELI_NS.WF_AP_YA_SALES_LE","MANKELI_NS.WF_ANAPLAN_FINANCEPLUG","MANKELI_NS.WF_FACT_HR","MANKELI_NS.WF_SII_CONTRACTOR_FTE","MANKELI_NS.WF_SII_KONSENSUS_ENNUSTE","MANKELI_NS.WF_SII_MANUAL_ACTLS","MANKELI_NS.WF_SII_MANUAL_PLN_FIG_LE","MANKELI_NS.WF_SII_MANUAL_PLN_FIG_STR","MANKELI_NS.WF_SII_MANUAL_PLN_FIG_TS","MANKELI_NS.WF_AP_CAPEX_SEGMENTS_ACT","MANKELI_NS.WF_AP_CAPEX_SEGMENTS_LE","MANKELI_NS.WF_AP_CAPEX_SEGMENTS_TS_STR","MANKELI_NS.WF_AP_TUKI_LOPPUKOHD_ACT","MANKELI_NS.WF_AP_TUKI_LOPPUKOHD_LE","MANKELI_NS.WF_AP_TUKI_LOPPUKOHD_TS_STR","MANKELI_NS.WF_AP_TUO_LOPPUKOHDISTUS_ACT","MANKELI_NS.WF_AP_TUO_LOPPUKOHDISTUS_LE","MANKELI_NS.WF_AP_TUO_LOPPUKOHDISTUS_TS_STR","MANKELI_NS.WF_AP_CAPEX_TS_STR","MANKELI_NS.WF_AP_CAPEX_TUO_TS_STR","MANKELI_NS.WF_AP_DEPRECIATIONS_TS_STR","MANKELI_NS.WF_AP_DEPRECIATIONS_TUO_TS_STR","MANKELI_NS.WF_AP_EXPENSES_IC_AND_ROAMING_TS_STR","MANKELI_NS.WF_AP_EXPENSES_TS_STR","MANKELI_NS.WF_AP_FTE_TS_STR","MANKELI_NS.WF_AP_HY_GENERAL_SALES_TS_STR","MANKELI_NS.WF_AP_KEYFIGURE_TS_STR","MANKELI_NS.WF_AP_OPERATOR_SALES_TS_STR","MANKELI_NS.WF_AP_OTHER_INCOME_TS_STR","MANKELI_NS.WF_AP_REVENUE_IC_AND_ROAMING_TS_STR","MANKELI_NS.WF_AP_SALES_ABPU_TS_STR","MANKELI_NS.WF_AP_SALES_BY_ACCOUNT_TS_STR","MANKELI_NS.WF_AP_SALES_VOLUME_TS_STR","MANKELI_NS.WF_AP_YA_SALES_TS_STR","MANKELI_NS.WF_ANAPLAN_SUBSIDIARY_FPA_ACTUAL","MANKELI_NS.WF_ANAPLAN_SUBSIDIARY_FPA_LE","MANKELI_NS.WF_ANAPLAN_SUBSIDIARY_FPA_STR","MANKELI_NS.WF_ANAPLANDRIVERS","MANKELI_NS.WF_ANAPLANHR","MANKELI_NS.WF_AP_ACTUALSTOANAPLAN_JOIKU","MANKELI_NS.WF_AP_ACTUALSTOANAPLANDATAHUB","MANKELI_NS.WF_AP_FORECASTTOANAPLAN_JOIKU","MANKELI_NS.WF_AP_JOIKU_MASTERDATA","MANKELI_NS.WF_SOR_ANAPLAN_ORGANISATION_ALLOCATION","MANKELI_NS.WF_SOR_ANAPLAN_ORGANISATION_ALLOCATION_LE","MANKELI_NS.WF_FACT_SAP_EXT_COMP_GENERIC_EXCEL","MANKELI_NS.WF_FACT_SAP_EXT_COMP_GENERIC_FLATFILE","MANKELI_NS.WF_FACT_SAP_TO_FACT_HR_BY_CC","MANKELI_NS.WF_JOIKU_BUSINESS_PORTFOLIO_ACT","MANKELI_NS.WF_JOIKU_BUSINESS_PORTFOLIO_LE","MANKELI_NS.WF_MDS_ALL","MANKELI_NS.WF_SOR_IM_MAP_ALL","MANKELI_NS.WF_SOR_SAP_CLOSED_PERIOD_CLOSE","MANKELI_NS.wf_FACT_PCA_BS_EXT_COMP_GENERIC_Excel","MANKELI_NS.wf_FACT_PCA_BS_EXT_COMP_GENERIC_FlatFile","MANKELI_NS.WF_DIM_VENDOR","MANKELI_NS.WF_FACT_GL_ENTRY","MANKELI_NS.WF_FACT_PLN_PROFITABILITY","MANKELI_NS.WF_MDS_ALL_JOIKU","SVOC_SOR.WF_SVOC_SOR_GL_DIM","SVOC_SOR.WF_SVOC_SOR_GLE","SVOC_SOR.WF_SVOC_SOR_GLE_GEN","SVOC_STG.WF_SVOC_STG_ABP_GLE_FIXED","SVOC_STG.WF_SVOC_STG_ABP_GLENTRY","SVOC_STG.WF_SVOC_STG_BASSET_GLENTRY"
                 ]

# --- Define Cell Formatting ---
# Define a bold font style, which will be used frequently
bold_font = Font(bold=True)

# Define the style for the "Note" cell (bold text with a yellow background)
note_font = Font(bold=True)
yellow_fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")

# --- Main Script Logic ---

# Loop through each workflow name in the input list
for workflow_name in INPUT_WF_LIST:
    try:
        # 1. Create a new Excel workbook in memory
        wb = openpyxl.Workbook()

        # 2. Configure the first sheet: "Table Status"
        sheet1 = wb.active
        sheet1.title = "Table Status"

        # Add content to the "Table Status" sheet
        sheet1['A2'] = workflow_name
        sheet1['B2'] = "Done"
        
        # Add and format the "Note" cell
        note_cell = sheet1['A6']
        note_cell.value = "Note"
        note_cell.font = note_font
        note_cell.fill = yellow_fill

        # 3. Configure the second sheet, named after the workflow
        sheet2 = wb.create_sheet(title=workflow_name)

        # Define the content for the second sheet (row_number, text)
        details_content = {
            1: "Table Name:",
            5: "Incremental Validation",
            6: "Incremental Run :",
            7: "Filter Used:",
            9: "Count Snippet:",
            17: "Data Snippet:"
        }

        # Add the defined content to the second sheet and make it bold
        for row_num, text in details_content.items():
            cell = sheet2.cell(row=row_num, column=1)
            cell.value = text
            cell.font = bold_font

        # 4. Save the workbook to a file
        # The filename will be the workflow name with an .xlsx extension
        filename = fr"C:\Users\punitkumar.more\Documents\Elisa\gcp_de\AUTOMATION\output\DOC2\{workflow_name}.xlsx"
        wb.save(filename)
        print(f"✅ Successfully created Excel file: {filename}")

    except Exception as e:
        print(f"❌ Failed to create file for {workflow_name}. Error: {e}")

print("\nScript finished.")